spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prowatchdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  quartz:
    job-store-type: jdbc

    jdbc:
      initialize-schema: never

    properties:
      org:
        quartz:

          scheduler:
            instanceName: QUARTZ_DB_SCHEDULER
            instanceId: AUTO

          threadPool:
            threadCount: 5

          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000